<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>jru.module3</groupId>
    <artifactId>project-maven</artifactId>
    <version>1.0</version>

    <properties>
        <maven.compiler.source>18</maven.compiler.source>
        <maven.compiler.target>18</maven.compiler.target>
    </properties>

    <dependencies>
        <!-- Пакет с утилитарными классами для классов из иерархии java.lang -->
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.12.0</version>
        </dependency>

        <!-- Зависимость для управления JavaFX -->
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>18.0.1</version>
        </dependency>

        <!-- javarush - По этой зависимости отдельное задание -->
        <dependency>
            <groupId>com.javarush</groupId>
            <artifactId>desktop-game-engine</artifactId>
            <version>1.0</version>
        </dependency>

        <!-- Основной пакет для тестового двигателя JUnit Jupiter -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.8.2</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <!-- Usual compilation - it was - NO Change -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version>
                <configuration>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>

            <!-- Run java-fx app over Maven - it was-->
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.8</version>
                <configuration>
                    <mainClass>com.javarush.games.racer.RacerGame</mainClass>
                </configuration>
            </plugin>

            <!-- Для Манифеста - какой класс является точкой входа-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.4.2</version>
                <configuration>
                    <archive>
                        <manifest>                                                                          <!-- создание сгенерированного манифеста на основе мэйн-класса -->
                            <addClasspath>true</addClasspath>
                            <mainClass>org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader</mainClass>    <!-- указывает на главный исполняемый класс -->
                        </manifest>
                        <manifestEntries>                                                                   <!-- позволяет добавлять собственные записи в манифест -->
                            <Rsrc-Main-Class>com.javarush.games.racer.RacerGame</Rsrc-Main-Class>           <!-- прописывается стартовый класс приложения -->
                            <classpathPrefix>lib/</classpathPrefix>                                         <!-- указывает префикс для всех зависимых JAR-файлов -->
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
                <version>3.0.0</version>
            </plugin>

            <!-- ЗАПУСК ТЕСТОВ -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <excludes>
                        <exclude>**/StrangeTest.java</exclude>                                              <!-- ИСКЛЮЧИТЬ ТЕСТ -->
                    </excludes>
                </configuration>
            </plugin>

            <!-- Плагин копирования зависимостей -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.6.1</version>
                <configuration>                                                                 <!-- копирование библиотек в директорию -->
                    <outputDirectory>${project.build.directory}/dependency</outputDirectory>
                    <includeScope>compile</includeScope>                        <!-- Фильтр: завис-ти, к-рые НЕ/попадут в /dependency, например, не включая scope test) -->
                </configuration>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>                                                  <!-- плагин будет вызван во время фазы сборки -->
                        <goals>
                            <goal>copy-dependencies</goal>                                      <!-- цель -> копировать зависимости проекта -->
                        </goals>
                    </execution>
                </executions>
            </plugin>

        </plugins>

        <resources>
            <resource>
                <directory>${project.build.directory}/lib</directory>                        <!-- куда будут копироваться зависимости во время сборки Maven-проекта -->
                <includes>
                    <include>*.jar</include>                                                 <!-- в сборку нужно включить все файлы .jar из указанной директории -->
                </includes>
            </resource>
        </resources>

    </build>

</project>